FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /code

# Instala dependências do sistema antes do pip install
RUN apt-get update && \
    apt-get install -y gcc default-libmysqlclient-dev pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
