# Generated by Django 4.2.23 on 2025-07-21 21:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Use o formato (XX) XXXXX-XXXX.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')])),
                ('cpf', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=300, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
                'db_table': 'coordenadores',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Use o formato (XX) XXXXX-XXXX.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')])),
                ('cpf', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('caf', models.CharField(max_length=100)),
                ('validade_caf', models.DateField()),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenador.coordenador')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
                'db_table': 'produtores',
                'ordering': ['nome', 'caf'],
            },
        ),
    ]
