# Generated by Django 4.2.23 on 2025-07-22 00:27

import coordenador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, validators=[coordenador.models.cpf_valido]),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, validators=[coordenador.models.cpf_valido]),
        ),
    ]
